In [66]:
import numpy as np

## Chapter - 1
### Numpy Basics

In [67]:
#array with defoult values
zeroes_array = np.zeros((2,3))
print(zeroes_array)

print()

#array with all ones
ones_array =  np.ones((2,3))
print(ones_array)

print()

#array of a specific value
filled_array = np.full((2,3), 7)
print(filled_array)

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[7 7 7]
 [7 7 7]]


In [68]:
#creating sequence of number
seq_arr = np.arange(0,10,2)   #(start,stop,step)
print(seq_arr)

[0 2 4 6 8]


In [69]:
#creating identity matrix
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Chapter - 2
### Array Propetrties & Operations

In [70]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr);   print()
print("shape:", arr.shape)
print("size:", arr.size)
print("no. of dimensions:", arr.ndim)
print("type of values:", arr.dtype)
arr = arr.astype(float); print("Data type changed to:", arr.dtype)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

shape: (3, 3)
size: 9
no. of dimensions: 2
type of values: int64
Data type changed to: float64


In [71]:
# For maths operation, it just does the operation with each element

#In-built operations 
print(np.sum(arr))    # Total sum of all elements
print(np.mean(arr))   # Mean (average) of all elements
print(np.min(arr))    # Minimum value
print(np.max(arr))    # Maximum value
print(np.std(arr))    # Standard deviation
print(np.var(arr))    # Variance

45.0
5.0
1.0
9.0
2.581988897471611
6.666666666666667


## Chapter - 3
### Indexing and Slicing 

In [72]:
#Indexing and Slicing
print(arr); print()

#Indexing 
print(arr[1, 2])

print()

#Slicing
print(arr[0:2, 1:]) #row 0-1, column 1-end

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

6.0

[[2. 3.]
 [5. 6.]]


In [73]:
#boolean maskong
print(arr[arr%2 == 0])

[2. 4. 6. 8.]


In [74]:
#Reshaping
arr1D = np.array([1,2,3,4,5,6])

print(arr1D.reshape(3,2))

print(arr1D)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [75]:
a = np.array([[1, 2], [3, 4]])

# ravel returns a view
r = np.ravel(a)
r[0] = 99
print(a)  # Original array is modified

# flatten returns a copy
f = a.flatten()
f[0] = 42
print(a)  # Original array remains unchanged


[[99  2]
 [ 3  4]]
[[99  2]
 [ 3  4]]


## Chapter - 4
### Reshaping & Manupulating Arrays

In [76]:
# Insert
print(arr); print()

insert_by_row = np.insert(arr, 3, [10,11,12], 0); print(insert_by_row); print()

insert_by_column = np.insert(arr, 3, [4,7,10], 1); print(insert_by_column)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]

[[ 1.  2.  3.  4.]
 [ 4.  5.  6.  7.]
 [ 7.  8.  9. 10.]]


In [77]:
#Concatenate
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[7,8,9]])     #make sure the no. of dimensions are same
c = np.concatenate((a,b), axis = 0); print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
#delete
arr_del = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(arr_del); print()


arr_del = np.delete(arr_del, 3, axis = 1);   print(arr_del)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
#stack

a = np.array([[1,2,3],
             [4,5,6]]);    print(a); print()
b = np.array([[7,8,9],
             [10,11,12]]);    print(b); print()

vert_stack = np.vstack((a,b)); print(vert_stack); print()
hozt_stack = np.hstack((a,b)); print(hozt_stack)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [80]:
#Split
split_c = np.array_split(c, 2, axis=0)

print("Split c part 1:\n", split_c[0])
print("Split c part 2:\n", split_c[1])






a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

# Split into 2 row blocks
np.vsplit(a, 2)




b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

# Split into 2 column blocks
np.hsplit(b, 2)



Split c part 1:
 [[1 2 3]
 [4 5 6]]
Split c part 2:
 [[7 8 9]]


[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

## Chapter - 5
### Broadcasting & Vectorizaion

In [81]:
prices = np.array([100,200,300])
discount = 10
final_price = prices - (prices*discount/100)
print(final_price)

[ 90. 180. 270.]


In [82]:
#Matrix and Vector Operations
matrix = np.array([[1,2,3],
                   [4,5,6]])

vector = np.array([10,20,30])

print("Element-wise Multiplication:\n", matrix * vector, "\n"); print()
print("Element-wise Addition:\n", matrix + vector, "\n"); print()
print("Element-wise Subtraction:\n", matrix - vector, "\n"); print()
print("Element-wise Division:\n", matrix / vector, "\n"); print()
print("Element-wise Power:\n", matrix ** vector, "\n"); print()

Element-wise Multiplication:
 [[ 10  40  90]
 [ 40 100 180]] 


Element-wise Addition:
 [[11 22 33]
 [14 25 36]] 


Element-wise Subtraction:
 [[ -9 -18 -27]
 [ -6 -15 -24]] 


Element-wise Division:
 [[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]] 


Element-wise Power:
 [[                  1             1048576     205891132094649]
 [            1048576      95367431640625 8138741398091333632]] 




## Chapter - 6
### Handling Missing & Special Values

In [83]:
# nan = not a number
arr = np.array([1, 2, 3, np.nan, 5, 6, np.nan, 7, 8, 9, 10, np.nan, 12])
print(np.isnan(arr))

[False False False  True False False  True False False False False  True
 False]


In [84]:
#Cleaning / replacing nan
arr = np.array([1, 2, 3, np.nan, 5, 6, np.nan, 7, 8, 9, 10, np.nan, 12])
cleaned_arr = np.nan_to_num(arr, nan = 100)
print(cleaned_arr)

[  1.   2.   3. 100.   5.   6. 100.   7.   8.   9.  10. 100.  12.]


In [92]:
arr = np.array([1, 2, 3, np.inf, 5, -np.inf])
print(np.isinf(arr)); print()
cleaned_arr = np.nan_to_num(arr, posinf = 1000, neginf = -1000)
print(cleaned_arr)

[False False False  True False  True]

[    1.     2.     3.  1000.     5. -1000.]


# More

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr.ndim)   #inbuilt function to check no. of dimension
print(arr.shape)  #No. of rows and columns

2
(2, 3)


In [ ]:
range = np.arange(0, 10, 2) #start, stop, step
print(range)

[0 2 4 6 8]


In [ ]:
arr = np.linspace(0,5,10) #start, stop, no. of values
print(arr)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
arr = np.logspace(1,3,3)
#start,stop ->powers,vales ->No. of vlaue in logarithmic space
print(arr)

[  10.  100. 1000.]


In [ ]:
arr = np.zeros([2,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.ones([2,3], dtype = int)
print(arr)

[[1 1 1]
 [1 1 1]]


In [ ]:
arr = np.full([2,3],7) #[row, column], default value
print(arr)

[[7 7 7]
 [7 7 7]]


In [ ]:
arr = np.empty([2,3])
print(arr)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


In [ ]:
arr = np.random.rand(2,3)
#no square brackets bcz its not taking any vlaues or any third parameter
arr

array([[0.08853961, 0.29082212, 0.11039362],
       [0.15292104, 0.82307818, 0.17596973]])

In [ ]:
arr = np.random.randn() 
#generates random samples from a normal distribution with mean 0 and standard deviation 1


In [ ]:
arr = np.random.randint(10, 100, [2,3]) #start, stop, dimension/no. of values
arr

array([[72, 78, 47],
       [29, 11, 31]], dtype=int32)

## NumPy Data Types and Type Casting

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
lst = ["string", 1, 2, 3.2]
lst = np.array(lst)
lst

array(['string', '1', '2', '3.2'], dtype='<U32')

In [ ]:
arr = np.array([1,2,3,4], dtype = np.float32)
arr

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
#Type Casting
arr = np.array([1,2,3])
print(arr.dtype)
new_arr = arr.astype(np.float64)
print(new_arr)
print(new_arr.dtype)

int64
[1. 2. 3.]
float64


In [ ]:
arr = np.array([1,2,3,4,5,6])
arr = arr.reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = arr.flatten()
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr = arr.reshape(2,3); print(arr)
arr = arr.ravel() #unlike flatten() it also changes the original array (it does not copy)
print(arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# Arthmetic Operations on Array

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a,b)

[1 2 3 4] [5 6 7 8]


In [ ]:
print(a+b)
print(b-a)
print(b*a)
print(b/a)
print(b*a)
print(b**a)
print(b%a)

[ 6  8 10 12]
[4 4 4 4]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]
[ 5 12 21 32]
[   5   36  343 4096]
[0 0 1 0]


# Universal Functions

In [ ]:
arr = np.array([1,4,9,16]); print(arr)
arr = np.sqrt(arr)
print(arr)


arr = np.array(arr,dtype=int)

[ 1  4  9 16]
[1. 2. 3. 4.]


In [ ]:
np.exp([1,2])   #e^1, e^2

array([2.71828183, 7.3890561 ])

In [ ]:
angles = np.array([0, np.pi, np.pi/2])
np.sin(angles)

array([0.0000000e+00, 1.2246468e-16, 1.0000000e+00])

In [ ]:
print(arr)
print(arr[-1:-4:-1])
print(arr[1::2])

[1 2 3 4]
[4 3 2]
[2 4]


In [ ]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(matrix[0:2, 0:2])   #rows slicing, column slicing

[[1 2]
 [4 5]]


In [ ]:
indices = np.array([[2, 1], [0, 2]])
print(np.take(matrix, indices, axis=1))

[[[3 2]
  [1 3]]

 [[6 5]
  [4 6]]

 [[9 8]
  [7 9]]]


In [ ]:
for x in matrix:
    print(x, end = " ")

print()

for x in np.nditer(matrix):
    print(x, end = " ")


[1 2 3] [4 5 6] [7 8 9] 
1 2 3 4 5 6 7 8 9 

In [ ]:
for idx, val in np.ndenumerate(matrix):
    print(idx, val)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [ ]:
#view
print(arr)
view = arr[1:3]; print(view)
view[0] = 20; print(view)
print(arr)

[1 2 3 4]
[2 3]
[20  3]
[ 1 20  3  4]


In [ ]:
#copy
copy = arr[0:3].copy() ; print(copy)
copy[0]= 10; print(copy)
print(arr)

[ 1 20  3]
[10 20  3]
[ 1 20  3  4]


In [ ]:
matrix.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
print(np.swapaxes(matrix,0,1))
print()

mt = np.array([[[1,2],[3,4]],
               [[5,6],[7,8]]])
print(np.swapaxes(mt,0,2))

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


In [ ]:
#Concatination
print(a)
print(b)

print()

ct = np.concatenate((a,b))
print(ct)

[1 2 3 4]
[5 6 7 8]

[1 2 3 4 5 6 7 8]


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

v = np.vstack((arr1, arr2)); print(v)
print()
h = np.hstack((arr1, arr2)); print(h)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
np.split(matrix, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [ ]:
np.hsplit(matrix, 3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [ ]:
np.vsplit(matrix, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [ ]:
np.tile(matrix,2)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [ ]:
print(arr)
print()

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.max(arr))
print(np.min(arr))
print(np.cumsum(arr))  #prints running total

[ 1 20  3  4]

28
7.0
3.5
7.582875444051551
20
1
[ 1 21 24 28]


In [ ]:
print(matrix)
print()
print(np.sum(matrix, axis = 0))
print()
print(np.sum(matrix, axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[12 15 18]

[ 6 15 24]


In [ ]:
#where
hl = np.where(matrix %2 == 0, "even", "odd")

print(matrix)
print()
print(hl)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[['odd' 'even' 'odd']
 ['even' 'odd' 'even']
 ['odd' 'even' 'odd']]
